apiVersion: v1
kind: Service
metadata:
  name: rest-spa
  labels:
    app: rest-spa-app
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http-server
  selector:
    app: rest-spa-app
    tier: frontend
