apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rest-spa
  labels:
    app: rest-spa-app
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: rest-spa-app
        tier: frontend
    spec:
      containers:
        - name: rest-spa-app
          image: 'gcr.io/spa-final-exam/rest-spa-app:latest'
          imagePullPolicy: Always
          ports:
            - name: http-server
              containerPort: 8000
